//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioColombia.Cliente.ServicioBienvenida {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/ColegioColombia.Wcf.Models")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioBienvenida.IServicioBienvenida")]
    public interface IServicioBienvenida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBienvenida/SaludoPersonalizado", ReplyAction="http://tempuri.org/IServicioBienvenida/SaludoPersonalizadoResponse")]
        string SaludoPersonalizado(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBienvenida/SaludoPersonalizado", ReplyAction="http://tempuri.org/IServicioBienvenida/SaludoPersonalizadoResponse")]
        System.Threading.Tasks.Task<string> SaludoPersonalizadoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBienvenida/ConsultarAlumno", ReplyAction="http://tempuri.org/IServicioBienvenida/ConsultarAlumnoResponse")]
        ColegioColombia.Cliente.ServicioBienvenida.Alumno ConsultarAlumno(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioBienvenida/ConsultarAlumno", ReplyAction="http://tempuri.org/IServicioBienvenida/ConsultarAlumnoResponse")]
        System.Threading.Tasks.Task<ColegioColombia.Cliente.ServicioBienvenida.Alumno> ConsultarAlumnoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioBienvenidaChannel : ColegioColombia.Cliente.ServicioBienvenida.IServicioBienvenida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBienvenidaClient : System.ServiceModel.ClientBase<ColegioColombia.Cliente.ServicioBienvenida.IServicioBienvenida>, ColegioColombia.Cliente.ServicioBienvenida.IServicioBienvenida {
        
        public ServicioBienvenidaClient() {
        }
        
        public ServicioBienvenidaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBienvenidaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBienvenidaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBienvenidaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaludoPersonalizado(string nombre) {
            return base.Channel.SaludoPersonalizado(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludoPersonalizadoAsync(string nombre) {
            return base.Channel.SaludoPersonalizadoAsync(nombre);
        }
        
        public ColegioColombia.Cliente.ServicioBienvenida.Alumno ConsultarAlumno(int id) {
            return base.Channel.ConsultarAlumno(id);
        }
        
        public System.Threading.Tasks.Task<ColegioColombia.Cliente.ServicioBienvenida.Alumno> ConsultarAlumnoAsync(int id) {
            return base.Channel.ConsultarAlumnoAsync(id);
        }
    }
}
